### ISSUE TITLE
UnsignedDeviceInfo in DeviceKeys should be mapped to 'unsigned'

### ISSUE THREAD

**Issue by rvillars** [ma1uta/jeon#13]
Hi, 

Thx for this framework!. It was very helpful and saved me a lot of time. Just one small thing I've found:
Currently the unsignedDeviceInfo property in the [DeviceKeys](https://github.com/ma1uta/jeon/blob/master/client-api/src/main/java/io/github/ma1uta/matrix/client/model/encryption/DeviceKeys.java) model class will be mapped to 'unsignedDeviceInfo' in JSON. 
This is wrong according to the Matrix Client-Server API spec. It should be mapped to 'unsigned'.

See https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-keys-query

Current:
```
"device_keys": {
    "@userId:homeserver": {
        "aDeviceId": {
            ...
            "unsignedDeviceInfo": {
                "device_display_name": "whatever"
            },
            "unsigned": {}
        }
    }
}
```

Correct:
```
"device_keys": {
    "@userId:homeserver": {
        "aDeviceId": {
            ...
            "unsigned": {
                "device_display_name": "whatever"
            }
        }
    }
}
```

**Comment by ma1uta** [comment]
Done in https://github.com/ma1uta/jeon/pull/10
