### ISSUE TITLE
Bump dependencies and new release?

### ISSUE THREAD

**Issue by brevilo** [ma1uta/jeon#7]
Hi! 

Development seems to be paused right now. Could you please consider bumping the dependencies again and push another release so that the latest version is available via maven?

Thanks and keep it up!

**Comment by ma1uta** [comment]
Done in https://github.com/ma1uta/jeon/commit/737bf5ae619dc5876f139d44cb0f6a97f19bfc9e
You can grad artifacts from https://repo1.maven.org/maven2/io/github/ma1uta/matrix/jeon/ in a few hours.
